---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebappauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mywebappauth
    spec:
      containers:
        - name: mywebappauth
          image: tomaslavinski/expensetrackerapiauth:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: mywebappauth
---
apiVersion: v1
kind: Service
metadata:
  name: mywebappauth
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: mywebappauth
