version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  main-api:
    build: ExpenseTracker/
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db-server
      - redis
    networks:
      - localdev
      
  auth-api:
    build: ExpenseTracker.AuthApi/
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - db-server
    networks:
      - localdev
        
  db-server:
    image: microsoft/mssql-server-linux
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Tomas1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"