---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: tomaslavinski/expensetrackerapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: mywebapp
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mywebapp
